### ISSUE TITLE
file instead of config option

### ISSUE THREAD

**Issue by bnomei** [moritzebeling/kirby-maintenance#1]
my janitor plugin has a maintenance mode as well. it uses a file instead of a config option to track its state. imho that makes it easier to toggle than inside php.

https://github.com/bnomei/kirby3-janitor/blob/57e9476966bcdd9ffea34878e26047d3402f253e/index.php#L94

i like the idea to have maintenance
mode in a seperate plugin. keep up the good work.

**Comment by moritzebeling** [comment]
Looks like Janitor has it all :) but I couldn’t find it when I was searching for `maintenance`. I myself prefer controlling site state through `config`. I now also added a panel field for toggling between both states. And I will also add your suggestion. 

Thank you for your comment!
